### ISSUE TITLE
Nativescript Angular: Can't find variable: BITHockeyManager

### ISSUE THREAD

**Issue by devCrossNet** [toddanglin/nativescript-hockey-sdk#1]
Hey,

I try to use this plugin because I have to prepare a beta test. I installed the plugin and used it in the `main.ts` file of my nativescript angular application.

Here is my code:

```
declare var BITHockeyManager: any;

app.on(app.launchEvent, (args: app.ApplicationEventData) => {  
  BITHockeyManager.sharedHockeyManager().configureWithIdentifier('APP_ID');
  BITHockeyManager.sharedHockeyManager().startManager();
  BITHockeyManager.sharedHockeyManager().authenticator.authenticateInstallation();
});
```

If I run my application it fails with the error message: `Can't find variable: BITHockeyManager`.

Do you know how to fix this issue? It is really important to me.

Thank you very much.

**Comment by tjvantoll** [comment]
Hey @devCrossNet,

I just gave this a shot on a newly created app with the following commands:

```
tns create foo --ng
cd foo
tns plugin add nativescript-hockey-sdk
tns run ios --emulator -watch
```

And then used the following for my `main.ts`:

``` TypeScript
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app.module";

declare var BITHockeyManager: any;

console.log(typeof BITHockeyManager);
platformNativeScriptDynamic().bootstrapModule(AppModule);
```

It logged `"function"`. Can you try this and see if works for you in a new app? Another thing to try is `rm -rf platforms/ node_modules` to force NativeScript to rebuild your iOS app from scratch as it’ll make sure the new plugin is included.

**Comment by devCrossNet** [comment]
@tjvantoll 

`rm -rf platforms/ node_modules` did it! Thank you very much :-) I just tried it with `tns prepare/build ios`. Now I have to figure out how to build it for hockey app.

I close this issue.

**Comment by tjvantoll** [comment]
No problem @devCrossNet, glad you got this working 😄
